version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: api-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/employeeDB
    depends_on:
      - mongo

  dbinit:
    build: ./server
    command: node scriptdb.js
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/employeeDB

  frontend:
    build: ./client
    container_name: vite-app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
